-- luacheck config for the MobaHUD addon:  luacheck client/addons/MobaHUD
-- apps/moba/deploy_addon.sh runs it before every copy into the client.

std = "lua51"   -- the client's dialect; 5.4+ accepts syntax 3.3.5 rejects

-- Generated by apps/moba/gen_store.py -- lint the generator, not its output.
exclude_files = { "Catalog.lua" }

-- Handler signatures are the client's, not ours: an OnUpdate that ignores `elapsed`
-- still has to declare it. ADDON_NAME is the same shape -- `local ADDON_NAME, ns = ...`
-- is the only way to reach ns.
unused_args = false
ignore = { "211/ADDON_NAME" }

-- The long lines here are inline texture escapes and the one-line command help, so a
-- limit only ever fires on lines that cannot be shortened.
max_line_length = false

-- Globals the addon assigns: its own, plus the client tables it registers into.
globals = {
    "BINDING_HEADER_MOBAHUD",
    "BINDING_NAME_MOBAHUD_TOGGLESHOP",
    "MobaHUDDB",
    "MobaHUD_ToggleShop",
    "MobaShopCatalog",
    "SLASH_MOBAHUD1",
    "SLASH_MOBAHUD2",
    "SlashCmdList",
}

-- The 3.3.5 client API this addon calls. A typo'd API name is the main thing this file
-- exists to catch, so extend the list as new calls appear rather than widening it.
read_globals = {
    "ClearCursor",
    "CreateFrame",
    "DEFAULT_CHAT_FRAME",
    "FauxScrollFrame_GetOffset",
    "FauxScrollFrame_OnVerticalScroll",
    "FauxScrollFrame_Update",
    "GameTooltip",
    "GetCoinTextureString",
    "GetCursorInfo",
    "GetCursorPosition",
    "GetItemIcon",
    "GetItemInfo",
    "GetTime",
    "IsInInstance",
    "Minimap",
    "MouseIsOver",
    "NUM_CONTAINER_FRAMES",
    "SendAddonMessage",
    "UIParent",
    "UISpecialFrames",
    "UnitLevel",
    "hooksecurefunc",
    "tinsert",
}
