USE acore_world;

-- ============================================================
-- Lane creep waves: 8 custom minion entries (2x melee, 1 caster, 1 siege
-- per team), each a full-stat copy of a real creature with a small set of
-- deliberate overrides (see .github/MOBA_GUIDE.md, "How to add a new
-- creep type"), plus their data-driven config table.
--
-- Levels are pinned to 80 (matching current tower/test-character level) --
-- the engine's aggro-range formula caps out at -25 levels difference, so
-- a low-level source template would barely aggro level-80 players.
--
-- Waypoint paths are NOT defined here. They are generated by
-- apps/moba/gen_creep_paths.py into data/sql/custom/mod_moba_creep_paths.sql;
-- the WaypointPathId values below are locked to lane/formation slots in
-- apps/moba/lane_config.lock.json.
-- ============================================================

DELETE FROM `creature_template` WHERE `entry` IN (900010, 900011, 900012, 900013, 900014, 900015, 900016, 900017);

INSERT INTO `creature_template`
(`entry`, `difficulty_entry_1`, `difficulty_entry_2`, `difficulty_entry_3`, `KillCredit1`, `KillCredit2`,
 `name`, `subname`, `IconName`, `gossip_menu_id`, `minlevel`, `maxlevel`, `exp`, `faction`, `npcflag`,
 `speed_walk`, `speed_run`, `speed_swim`, `speed_flight`, `detection_range`, `rank`, `dmgschool`, `DamageModifier`,
 `BaseAttackTime`, `RangeAttackTime`, `BaseVariance`, `RangeVariance`, `unit_class`, `unit_flags`, `unit_flags2`,
 `dynamicflags`, `family`, `type`, `type_flags`, `lootid`, `pickpocketloot`, `skinloot`, `PetSpellDataId`,
 `VehicleId`, `mingold`, `maxgold`, `AIName`, `MovementType`, `HoverHeight`, `HealthModifier`, `ManaModifier`,
 `ArmorModifier`, `ExperienceModifier`, `RacialLeader`, `movementId`, `RegenHealth`, `CreatureImmunitiesId`,
 `flags_extra`, `ScriptName`, `VerifiedBuild`)
VALUES
-- Melee, from 2279/2280 'Battleguard'
(900010,0,0,0,0,0,'Alliance Footman','MOBA Minion',NULL,0,80,80,0,84,0,
 1.2,1.14286,1,1,20,0,0,1,2000,2000,1,1,1,0,2048,0,0,7,0,0,0,0,0,
 0,0,0,'',0,1,0.15,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
(900016,0,0,0,0,0,'Alliance Footman','MOBA Minion',NULL,0,80,80,0,84,0,
 1.2,1.14286,1,1,20,0,0,1,2000,2000,1,1,1,0,2048,0,0,7,0,0,0,0,0,
 0,0,0,'',0,1,0.15,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
(900011,0,0,0,0,0,'Horde Grunt','MOBA Minion',NULL,0,80,80,0,83,0,
 1.2,1.14286,1,1,20,0,0,1,2000,2000,1,1,1,0,2048,0,0,7,0,0,0,0,0,
 0,0,0,'',0,1,0.15,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
(900017,0,0,0,0,0,'Horde Grunt','MOBA Minion',NULL,0,80,80,0,83,0,
 1.2,1.14286,1,1,20,0,0,1,2000,2000,1,1,1,0,2048,0,0,7,0,0,0,0,0,
 0,0,0,'',0,1,0.15,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
-- Caster, from 1914 'Dalaran Mage' / 11683 'Warsong Shaman'
(900012,0,0,0,0,0,'Alliance Mage','MOBA Minion',NULL,0,80,80,0,84,0,
 1,1.14286,1,1,18,0,0,1,2000,2000,1,1,8,0,2048,0,0,7,0,0,0,0,0,
 0,12,38,'',1,1,0.15,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
(900013,0,0,0,0,0,'Horde Shaman','MOBA Minion',NULL,0,80,80,0,83,0,
 1,1.14286,1,1,20,0,0,1,2000,2000,1,1,8,32768,2048,0,0,7,0,0,0,0,0,
 0,37,53,'',0,1,0.15,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
-- Siege, from 34775 'Demolisher' (npcflag/VehicleId zeroed -- mount/vehicle baggage;
-- movementId/CreatureImmunitiesId zeroed -- Demolisher-specific, not confirmed vehicle-safe;
-- RegenHealth set to 1 for consistency, overriding the vehicle default of 0)
(900014,0,0,0,0,0,'Alliance Demolisher','MOBA Minion',NULL,0,80,80,0,84,0,
 1.2,0.98571,1,1,20,1,0,1,2000,2000,1,1,1,16384,2048,0,0,9,131080,0,0,0,0,
 0,0,0,'',0,1,0.3,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0),
(900015,0,0,0,0,0,'Horde Demolisher','MOBA Minion',NULL,0,80,80,0,83,0,
 1.2,0.98571,1,1,20,1,0,1,2000,2000,1,1,1,16384,2048,0,0,9,131080,0,0,0,0,
 0,0,0,'',0,1,0.3,1,0.25,1,0,0,1,0,0,'npc_moba_creep',0);

DELETE FROM `creature_template_model` WHERE `CreatureID` IN (900010, 900011, 900012, 900013, 900014, 900015, 900016, 900017);
INSERT INTO `creature_template_model` (`CreatureID`, `Idx`, `CreatureDisplayID`, `DisplayScale`, `Probability`, `VerifiedBuild`)
VALUES
(900010, 0, 164, 1.0, 1, 0),
(900016, 0, 164, 1.0, 1, 0),
(900011, 0, 496, 1.0, 1, 0),
(900017, 0, 496, 1.0, 1, 0),
(900012, 0, 3559, 1.0, 1, 0),
(900013, 0, 11865, 1.0, 1, 0),
(900014, 0, 27658, 1.0, 1, 0),
(900015, 0, 27658, 1.0, 1, 0);

-- ============================================================
-- Per-creep data-driven config: role, attack stats (caster only), lane
-- path, and despawn timing. Mirrors mod_moba_tower_data's approach --
-- see MobaCreepData.h/.cpp.
-- Role: 0 = melee, 1 = caster, 2 = siege.
-- AttackRange/AttackIntervalMs/AttackSpellId only apply to casters
-- (melee/siege rely on default engine auto-attack, no custom cast).
-- Caster spells match what the source mobs cast via their original
-- SmartAI (smart_scripts 1914/11683): real cast time and mana cost.
-- ============================================================
DROP TABLE IF EXISTS `mod_moba_creep_data`;
CREATE TABLE `mod_moba_creep_data` (
    `CreatureEntry`    INT UNSIGNED NOT NULL PRIMARY KEY,
    `Team`             TINYINT UNSIGNED NOT NULL,      -- TeamId: 0 = Alliance, 1 = Horde
    `Role`             TINYINT UNSIGNED NOT NULL,       -- 0=melee, 1=caster, 2=siege
    `AttackRange`      FLOAT NOT NULL DEFAULT 20,
    `AttackIntervalMs` INT UNSIGNED NOT NULL DEFAULT 2000,
    `AttackSpellId`    INT UNSIGNED NOT NULL DEFAULT 0,
    `WaypointPathId`   INT UNSIGNED NOT NULL,
    `DespawnMs`        INT UNSIGNED NOT NULL DEFAULT 60000
);

INSERT INTO `mod_moba_creep_data`
(`CreatureEntry`, `Team`, `Role`, `AttackRange`, `AttackIntervalMs`, `AttackSpellId`, `WaypointPathId`, `DespawnMs`)
VALUES
(900010, 0, 0, 20, 2000, 0,     900110, 60000), -- Alliance melee   (lane slot: mid/melee_right forward)
(900016, 0, 0, 20, 2000, 0,     900111, 60000), -- Alliance melee   (lane slot: mid/melee_left forward)
(900011, 1, 0, 20, 2000, 0,     900120, 60000), -- Horde melee      (lane slot: mid/melee_right reverse)
(900017, 1, 0, 20, 2000, 0,     900121, 60000), -- Horde melee      (lane slot: mid/melee_left reverse)
(900012, 0, 1, 20, 2000, 20793, 900100, 60000), -- Alliance Mage: Fireball       (mid/caster forward)
(900013, 1, 1, 20, 2000, 20805, 900101, 60000), -- Horde Shaman: Lightning Bolt  (mid/caster reverse)
(900014, 0, 2, 20, 2000, 0,     900112, 60000), -- Alliance Demolisher (mid/siege forward)
(900015, 1, 2, 20, 2000, 0,     900122, 60000); -- Horde Demolisher    (mid/siege reverse)

-- Weapons: creature_equip_template is a separate table not covered by the
-- creature_template full-copy -- without it the melee swing unarmed (barely
-- visible on the human model). Items copied from the source creatures
-- (2279/2280 Battleguard, 1914 Dalaran Mage, 11683 Warsong Shaman).
-- Summons auto-load equipment ID 1 (Creature::LoadEquipment default).
DELETE FROM `creature_equip_template` WHERE `CreatureID` IN (900010, 900011, 900012, 900013, 900016, 900017);
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`)
VALUES
(900010, 1, 1899, 143,  0, 0), -- Alliance melee: sword + shield
(900016, 1, 1899, 143,  0, 0),
(900011, 1, 2183, 2051, 0, 0), -- Horde melee: axe + shield
(900017, 1, 2183, 2051, 0, 0),
(900012, 1, 2177, 0,    0, 0), -- Alliance Mage: staff
(900013, 1, 5303, 0,    0, 0); -- Horde Shaman: staff